-- Migración: tabla RESULTADO_FUERZA para persistir puntuaciones del
-- medidor de fuerza y torneos. Idempotente.

BEGIN;

CREATE TABLE IF NOT EXISTS RESULTADO_FUERZA (
    ID_RESULTADO SERIAL PRIMARY KEY,
    ID_USUARIO INTEGER,
    NOMBRE_PARTICIPANTE VARCHAR(50) NOT NULL,
    PUNTUACION INTEGER NOT NULL DEFAULT 0,
    MODO VARCHAR(20) NOT NULL DEFAULT 'Medidor',
    GRUPO VARCHAR(36),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resultado_fuerza_usuario
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_resultado_fuerza_usuario ON RESULTADO_FUERZA (ID_USUARIO);
CREATE INDEX IF NOT EXISTS idx_resultado_fuerza_grupo ON RESULTADO_FUERZA (GRUPO);

COMMIT;
