//! Persistencia de muestras BLE en PostgreSQL.
//!
//! Este modulo define:
//! - El modelo `BleSample` para cada lectura recibida.
//! - `SampleWriter`, que desacopla recepcion de datos y escritura a BD.
//! - Un loop de escritura por lotes con transacciones.

use std::env;
use std::error::Error;
use tokio::sync::mpsc;
use tokio::time::{Duration, interval};
use tokio_postgres::{Client, NoTls, Statement};
use tracing::{debug, error, info};

/// Muestra de telemetria decodificada que se persiste en la base de datos.
#[derive(Debug, Clone)]
pub struct BleSample {
    pub device_mac: String,
    pub device_name: String,
    pub ble_ts: Option<i32>,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

/// Lectura de nivel de bateria BLE.
#[derive(Debug, Clone)]
pub struct BatteryReading {
    pub device_mac: String,
    pub device_name: String,
    pub battery_level: i16,
}

/// Registro unificado para el canal de escritura a BD.
#[derive(Debug, Clone)]
pub enum DbRecord {
    Sample(BleSample),
    Battery(BatteryReading),
}

/// Estadisticas para monitorear rendimiento del escritor.
#[derive(Clone, Copy, Debug)]
struct WriterStats {
    total_samples: usize,
    last_report: std::time::Instant,
    per_commit_samples: usize,
    samples_per_second: f64,
}
impl WriterStats {
    fn new() -> Self {
        Self {
            total_samples: 0,
            last_report: std::time::Instant::now(),
            per_commit_samples: 0,
            samples_per_second: 0.0,
        }
    }
}
/// Escritor asincrono basado en canal para enviar muestras a PostgreSQL.
///
/// La idea es evitar que el loop de lectura BLE quede bloqueado por I/O de base de datos.
#[derive(Clone)]
pub struct DbWritter {
    tx: mpsc::Sender<DbRecord>,
}

impl DbWritter {
    /// Crea la conexion a PostgreSQL, inicializa schema y arranca el loop de escritura.
    pub async fn connect(database_url: &str) -> Result<Self, Box<dyn Error>> {
        info!("Connecting to PostgreSQL at {}", database_url);
        let (client, connection) = match tokio_postgres::connect(database_url, NoTls).await {
            Ok((client, connection)) => {
                info!("Successfully connected to PostgreSQL");
                (client, connection)
            }
            Err(err) => {
                error!("PostgreSQL connection error: {}", err);
                return Err(Box::new(err));
            }
        };

        // Task de mantenimiento para reportar errores de la conexion subyacente.
        tokio::spawn(async move {
            if let Err(err) = connection.await {
                error!("PostgreSQL connection error: {}", err);
            }
        });

        // Crea tabla e indice si aun no existen.
        if let Err(err) = init_schema(&client).await {
            error!("PostgreSQL schema initialization error: {}", err);
            return Err(Box::new(err));
        }

        // Canal bufferizado para desacoplar productor (BLE) de consumidor (BD).
        let (tx, rx) = mpsc::channel(4096);
        tokio::spawn(async move {
            writer_loop(client, rx).await;
        });

        info!("PostgreSQL writer is ready");
        Ok(Self { tx })
    }

    /// Encola una muestra para que sea persistida por el writer en segundo plano.
    pub async fn send_sample(
        &self,
        sample: BleSample,
    ) -> Result<(), mpsc::error::SendError<DbRecord>> {
        self.tx.send(DbRecord::Sample(sample)).await
    }

    /// Encola una lectura de bateria para que sea persistida por el writer en segundo plano.
    pub async fn send_battery(
        &self,
        reading: BatteryReading,
    ) -> Result<(), mpsc::error::SendError<DbRecord>> {
        self.tx.send(DbRecord::Battery(reading)).await
    }
}

/// Garantiza que la tabla destino y su indice existan.
async fn init_schema(client: &Client) -> Result<(), tokio_postgres::Error> {
    client
        .batch_execute(
            "
            CREATE EXTENSION IF NOT EXISTS timescaledb;

            CREATE TABLE IF NOT EXISTS ble_samples (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                device_mac TEXT NOT NULL,
                device_name TEXT NOT NULL,
                ble_ts INTEGER,
                x REAL NOT NULL,
                y REAL NOT NULL,
                z REAL NOT NULL,
                received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (received_at, id)
            );

            SELECT create_hypertable('ble_samples', 'received_at', if_not_exists => TRUE, migrate_data => TRUE);

            CREATE INDEX IF NOT EXISTS idx_ble_samples_received_at ON ble_samples(received_at);

            CREATE TABLE IF NOT EXISTS device_battery_readings (
                id BIGSERIAL PRIMARY KEY,
                device_mac TEXT NOT NULL,
                device_name TEXT NOT NULL,
                battery_level SMALLINT NOT NULL,
                read_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS idx_battery_read_at ON device_battery_readings(read_at);
            CREATE INDEX IF NOT EXISTS idx_battery_device ON device_battery_readings(device_mac);
            ",
        )
        .await
}

/// Loop principal del escritor: acumula en memoria y descarga periodicamente por lotes.
///
/// Estrategia de flush:
/// - Inmediato al alcanzar 128 muestras.
/// - Periodico cada 50 ms si hay datos pendientes.
/// - Final al cerrar el canal.
async fn writer_loop(mut client: Client, mut rx: mpsc::Receiver<DbRecord>) {
    let mut stats = WriterStats::new();

    let insert_stmt = match client
        .prepare(
            "
            INSERT INTO ble_samples (device_mac, device_name, ble_ts, x, y, z)
            VALUES ($1, $2, $3, $4, $5, $6)
            ",
        )
        .await
    {
        Ok(stmt) => stmt,
        Err(err) => {
            error!("failed to prepare insert statement: {}", err);
            return;
        }
    };

    let battery_stmt = match client
        .prepare(
            "
            INSERT INTO device_battery_readings (device_mac, device_name, battery_level)
            VALUES ($1, $2, $3)
            ",
        )
        .await
    {
        Ok(stmt) => stmt,
        Err(err) => {
            error!("failed to prepare battery insert statement: {}", err);
            return;
        }
    };

    // Tick periodico para limitar latencia en lotes pequenos.
    let mut tick = interval(Duration::from_millis(
        env::var("FLUSH_INTERVAL_MS")
            .unwrap_or("50".to_string())
            .parse()
            .unwrap_or(50),
    ));

    // Tick para reportar tasa de datos cada 5 segundos.
    let mut info_tick = interval(Duration::from_secs(5));
    // Buffer reusable para minimizar realocaciones.
    let mut buffer: Vec<DbRecord> = Vec::with_capacity(256);

    // Loop principal: espera 128 registros o 50 ms para enviar un lote.
    loop {
        tokio::select! {
            maybe_record = rx.recv() => {
                match maybe_record {
                    Some(record) => {
                        if let DbRecord::Sample(ref sample) = record
                            && (-20000.0 > sample.z || sample.z > 20000.0) {
                                debug!("discarding outlier sample: {:?}", sample);
                                continue;
                            }
                        buffer.push(record);
                        // Umbral de lote: reduce costo por transaccion.
                        if buffer.len() >= 128 {
                            flush_batch(&mut client, &insert_stmt, &battery_stmt, &mut buffer, &mut stats).await;
                        }
                    }
                    None => {
                        if !buffer.is_empty() {
                            flush_batch(&mut client, &insert_stmt, &battery_stmt, &mut buffer, &mut stats).await;
                        }
                        info!("sample channel closed, writer loop stopping");
                        break;
                    }
                }
            }
            _ = tick.tick() => {
                if !buffer.is_empty() {
                    flush_batch(&mut client, &insert_stmt, &battery_stmt, &mut buffer, &mut stats).await;
                }
            }
            _ = info_tick.tick() => {
                let elapsed = stats.last_report.elapsed().as_secs_f64();
                if elapsed > 0.0 {
                    info!("total samples: {}, last batch: {}, rate: {:.2} samples/s",
                        stats.total_samples, stats.per_commit_samples, stats.samples_per_second);
                }
            }
        }
    }
}

/// Persiste un lote dentro de una transaccion unica.
///
/// Si ocurre un error durante insercion o commit, se reporta y el lote no se confirma.
async fn flush_batch(
    client: &mut Client,
    stmt: &Statement,
    battery_stmt: &Statement,
    buffer: &mut Vec<DbRecord>,
    stats: &mut WriterStats,
) {
    // Mueve el contenido del buffer para liberar al productor cuanto antes.
    let mut pending = Vec::with_capacity(buffer.len());
    pending.append(buffer);

    let tx = match client.transaction().await {
        Ok(tx) => tx,
        Err(err) => {
            // TODO: retry connection to client

            error!("failed to start transaction: {}", err);
            return;
        }
    };

    for record in &pending {
        match record {
            DbRecord::Sample(sample) => {
                if let Err(err) = tx
                    .execute(
                        stmt,
                        &[
                            &sample.device_mac,
                            &sample.device_name,
                            &sample.ble_ts,
                            &sample.x,
                            &sample.y,
                            &sample.z,
                        ],
                    )
                    .await
                {
                    error!("failed to insert sample: {}", err);
                    return;
                }
            }
            DbRecord::Battery(reading) => {
                if let Err(err) = tx
                    .execute(
                        battery_stmt,
                        &[
                            &reading.device_mac,
                            &reading.device_name,
                            &reading.battery_level,
                        ],
                    )
                    .await
                {
                    error!("failed to insert battery reading: {}", err);
                    return;
                }
            }
        }
    }

    if let Err(err) = tx.commit().await {
        error!("failed to commit sample batch: {}", err);
        return;
    }
    stats.total_samples += pending.len();
    stats.per_commit_samples = pending.len();
    let elapsed = stats.last_report.elapsed().as_secs_f64();
    if elapsed > 0.0 {
        let current_rate = pending.len() as f64 / elapsed;
        stats.samples_per_second = stats.samples_per_second * 0.8 + current_rate * 0.2;
    }
    stats.last_report = std::time::Instant::now();

    debug!("flushed {} records", pending.len());
}
