//! Persistencia de muestras BLE en PostgreSQL.
//!
//! Este modulo define:
//! - El modelo `BleSample` para cada lectura recibida.
//! - `SampleWriter`, que desacopla recepcion de datos y escritura a BD.
//! - Un loop de escritura por lotes con transacciones.

use std::error::Error;

use tokio::sync::mpsc;
use tokio::time::{Duration, interval};
use tokio_postgres::{Client, NoTls, Statement};
use tracing::{debug, error, info};

/// Muestra de telemetria decodificada que se persiste en la base de datos.
#[derive(Debug, Clone)]
pub struct BleSample {
    pub device_mac: String,
    pub device_name: String,
    pub ble_ts: Option<i32>,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

/// Escritor asincrono basado en canal para enviar muestras a PostgreSQL.
///
/// La idea es evitar que el loop de lectura BLE quede bloqueado por I/O de base de datos.
pub struct SampleWriter {
    tx: mpsc::Sender<BleSample>,
}

impl SampleWriter {
    /// Crea la conexion a PostgreSQL, inicializa schema y arranca el loop de escritura.
    pub async fn connect(database_url: &str) -> Result<Self, Box<dyn Error>> {
        let (client, connection) = match tokio_postgres::connect(database_url, NoTls).await {
            Ok((client, connection)) => (client, connection),
            Err(err) => {
                error!("PostgreSQL connection error: {}", err);
                return Err(Box::new(err));
            }
        };

        // Task de mantenimiento para reportar errores de la conexion subyacente.
        tokio::spawn(async move {
            if let Err(err) = connection.await {
                error!("PostgreSQL connection error: {}", err);
            }
        });

        // Crea tabla e indice si aun no existen.
        if let Err(err) = init_schema(&client).await {
            error!("PostgreSQL schema initialization error: {}", err);
            return Err(Box::new(err));
        }

        // Canal bufferizado para desacoplar productor (BLE) de consumidor (BD).
        let (tx, rx) = mpsc::channel(4096);
        tokio::spawn(async move {
            writer_loop(client, rx).await;
        });

        info!("PostgreSQL writer is ready");
        Ok(Self { tx })
    }

    /// Encola una muestra para que sea persistida por el writer en segundo plano.
    pub async fn send(&self, sample: BleSample) -> Result<(), mpsc::error::SendError<BleSample>> {
        self.tx.send(sample).await
    }
}

/// Garantiza que la tabla destino y su indice existan.
async fn init_schema(client: &Client) -> Result<(), tokio_postgres::Error> {
    client
        .batch_execute(
            "
            CREATE EXTENSION IF NOT EXISTS timescaledb;

            CREATE TABLE IF NOT EXISTS ble_samples (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                device_mac TEXT NOT NULL,
                device_name TEXT NOT NULL,
                ble_ts INTEGER,
                x REAL NOT NULL,
                y REAL NOT NULL,
                z REAL NOT NULL,
                received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (received_at, id)
            );

            SELECT create_hypertable('ble_samples', 'received_at', if_not_exists => TRUE, migrate_data => TRUE);

            CREATE INDEX IF NOT EXISTS idx_ble_samples_received_at ON ble_samples(received_at);
            ",
        )
        .await
}

/// Loop principal del escritor: acumula en memoria y descarga periodicamente por lotes.
///
/// Estrategia de flush:
/// - Inmediato al alcanzar 128 muestras.
/// - Periodico cada 50 ms si hay datos pendientes.
/// - Final al cerrar el canal.
async fn writer_loop(mut client: Client, mut rx: mpsc::Receiver<BleSample>) {
    let insert_stmt = match client
        .prepare(
            "
            INSERT INTO ble_samples (device_mac, device_name, ble_ts, x, y, z)
            VALUES ($1, $2, $3, $4, $5, $6)
            ",
        )
        .await
    {
        Ok(stmt) => stmt,
        Err(err) => {
            error!("failed to prepare insert statement: {}", err);
            return;
        }
    };

    // Tick periodico para limitar latencia en lotes pequenos.
    let mut tick = interval(Duration::from_millis(50));
    // Buffer reusable para minimizar realocaciones.
    let mut buffer: Vec<BleSample> = Vec::with_capacity(256);

    // Loop principal: espera 128 muestras o 50 ms para enviar un lote.
    loop {
        tokio::select! {
            maybe_sample = rx.recv() => {
                match maybe_sample {
                    Some(sample) => {
                        buffer.push(sample);
                        // Umbral de lote: reduce costo por transaccion.
                        if buffer.len() >= 128 {
                            flush_batch(&mut client, &insert_stmt, &mut buffer).await;
                        }
                    }
                    None => {
                        if !buffer.is_empty() {
                            flush_batch(&mut client, &insert_stmt, &mut buffer).await;
                        }
                        info!("sample channel closed, writer loop stopping");
                        break;
                    }
                }
            }
            _ = tick.tick() => {
                if !buffer.is_empty() {
                    flush_batch(&mut client, &insert_stmt, &mut buffer).await;
                }
            }
        }
    }
}

/// Persiste un lote dentro de una transaccion unica.
///
/// Si ocurre un error durante insercion o commit, se reporta y el lote no se confirma.
async fn flush_batch(client: &mut Client, stmt: &Statement, buffer: &mut Vec<BleSample>) {
    // Mueve el contenido del buffer para liberar al productor cuanto antes.
    let mut pending = Vec::with_capacity(buffer.len());
    pending.append(buffer);

    let tx = match client.transaction().await {
        Ok(tx) => tx,
        Err(err) => {
            error!("failed to open transaction: {}", err);
            return;
        }
    };

    for sample in &pending {
        if let Err(err) = tx
            .execute(
                stmt,
                &[
                    &sample.device_mac,
                    &sample.device_name,
                    &sample.ble_ts,
                    &sample.x,
                    &sample.y,
                    &sample.z,
                ],
            )
            .await
        {
            error!("failed to insert sample: {}", err);
            return;
        }
    }

    if let Err(err) = tx.commit().await {
        error!("failed to commit sample batch: {}", err);
        return;
    }

    debug!("flushed {} samples", pending.len());
    info!("Data rate: {:.2} samples/sec", pending.len() as f64 / 0.05);
}
