//! Persistencia de muestras BLE en PostgreSQL.
//!
//! Este modulo define:
//! - El modelo `BleSample` para cada lectura recibida.
//! - `SampleWriter`, que desacopla recepcion de datos y escritura a BD.
//! - Un loop de escritura por lotes con transacciones.

use std::env;
use std::error::Error;
use tokio::sync::mpsc;
use tokio::time::{Duration, interval};
use tokio_postgres::{Client, NoTls, Statement};
use tracing::{debug, error, info};

/// Muestra de telemetria decodificada que se persiste en la base de datos.
#[derive(Debug, Clone)]
pub struct BleSample {
    pub device_mac: String,
    pub device_name: String,
    pub ble_ts: Option<i32>,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

/// Estadisticas para monitorear rendimiento del escritor.
#[derive(Clone, Copy, Debug)]
struct WriterStats {
    total_samples: usize,
    last_report: std::time::Instant,
    per_commit_samples: usize,
    samples_per_second: f64,
}
impl WriterStats {
    fn new() -> Self {
        Self {
            total_samples: 0,
            last_report: std::time::Instant::now(),
            per_commit_samples: 0,
            samples_per_second: 0.0,
        }
    }
}
/// Escritor asincrono basado en canal para enviar muestras a PostgreSQL.
///
/// La idea es evitar que el loop de lectura BLE quede bloqueado por I/O de base de datos.
pub struct SampleWriter {
    tx: mpsc::Sender<BleSample>,
}

impl SampleWriter {
    /// Crea la conexion a PostgreSQL, inicializa schema y arranca el loop de escritura.
    pub async fn connect(database_url: &str) -> Result<Self, Box<dyn Error>> {
        let (client, connection) = match tokio_postgres::connect(database_url, NoTls).await {
            Ok((client, connection)) => (client, connection),
            Err(err) => {
                error!("PostgreSQL connection error: {}", err);
                return Err(Box::new(err));
            }
        };

        // Task de mantenimiento para reportar errores de la conexion subyacente.
        tokio::spawn(async move {
            if let Err(err) = connection.await {
                error!("PostgreSQL connection error: {}", err);
            }
        });

        // Crea tabla e indice si aun no existen.
        if let Err(err) = init_schema(&client).await {
            error!("PostgreSQL schema initialization error: {}", err);
            return Err(Box::new(err));
        }

        // Canal bufferizado para desacoplar productor (BLE) de consumidor (BD).
        let (tx, rx) = mpsc::channel(4096);
        tokio::spawn(async move {
            writer_loop(client, rx).await;
        });

        info!("PostgreSQL writer is ready");
        Ok(Self { tx })
    }

    /// Encola una muestra para que sea persistida por el writer en segundo plano.
    pub async fn send(&self, sample: BleSample) -> Result<(), mpsc::error::SendError<BleSample>> {
        self.tx.send(sample).await
    }
}

/// Garantiza que la tabla destino y su indice existan.
async fn init_schema(client: &Client) -> Result<(), tokio_postgres::Error> {
    client
        .batch_execute(
            "
            CREATE EXTENSION IF NOT EXISTS timescaledb;

            CREATE TABLE IF NOT EXISTS ble_samples (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                device_mac TEXT NOT NULL,
                device_name TEXT NOT NULL,
                ble_ts INTEGER,
                x REAL NOT NULL,
                y REAL NOT NULL,
                z REAL NOT NULL,
                received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (received_at, id)
            );

            SELECT create_hypertable('ble_samples', 'received_at', if_not_exists => TRUE, migrate_data => TRUE);

            CREATE INDEX IF NOT EXISTS idx_ble_samples_received_at ON ble_samples(received_at);
            ",
        )
        .await
}

/// Loop principal del escritor: acumula en memoria y descarga periodicamente por lotes.
///
/// Estrategia de flush:
/// - Inmediato al alcanzar 128 muestras.
/// - Periodico cada 50 ms si hay datos pendientes.
/// - Final al cerrar el canal.
async fn writer_loop(mut client: Client, mut rx: mpsc::Receiver<BleSample>) {
    let mut stats = WriterStats::new();

    let insert_stmt = match client
        .prepare(
            "
            INSERT INTO ble_samples (device_mac, device_name, ble_ts, x, y, z)
            VALUES ($1, $2, $3, $4, $5, $6)
            ",
        )
        .await
    {
        Ok(stmt) => stmt,
        Err(err) => {
            error!("failed to prepare insert statement: {}", err);
            return;
        }
    };

    // Tick periodico para limitar latencia en lotes pequenos.
    let mut tick = interval(Duration::from_millis(
        env::var("FLUSH_INTERVAL_MS")
            .unwrap_or("50".to_string())
            .parse()
            .unwrap_or(50),
    ));

    // Tick para reportar tasa de datos cada 5 segundos.
    let mut info_tick = interval(Duration::from_secs(5));
    // Buffer reusable para minimizar realocaciones.
    let mut buffer: Vec<BleSample> = Vec::with_capacity(256);

    // Loop principal: espera 128 muestras o 50 ms para enviar un lote.
    loop {
        tokio::select! {
            maybe_sample = rx.recv() => {
                match maybe_sample {
                    Some(sample) => {
                        buffer.push(sample);
                        // Umbral de lote: reduce costo por transaccion.
                        if buffer.len() >= 128 {
                            flush_batch(&mut client, &insert_stmt, &mut buffer, &mut stats).await;
                        }
                    }
                    None => {
                        if !buffer.is_empty() {
                            flush_batch(&mut client, &insert_stmt, &mut buffer, &mut stats).await;
                        }
                        info!("sample channel closed, writer loop stopping");
                        break;
                    }
                }
            }
            _ = tick.tick() => {
                if !buffer.is_empty() {
                    flush_batch(&mut client, &insert_stmt, &mut buffer, &mut stats).await;
                }
            }
            _ = info_tick.tick() => {
                let elapsed = stats.last_report.elapsed().as_secs_f64();
                if elapsed > 0.0 {
                    info!("total samples: {}, last batch: {}, rate: {:.2} samples/s",
                        stats.total_samples, stats.per_commit_samples, stats.samples_per_second);
                }
            }
        }
    }
}

/// Persiste un lote dentro de una transaccion unica.
///
/// Si ocurre un error durante insercion o commit, se reporta y el lote no se confirma.
async fn flush_batch(
    client: &mut Client,
    stmt: &Statement,
    buffer: &mut Vec<BleSample>,
    stats: &mut WriterStats,
) {
    // Mueve el contenido del buffer para liberar al productor cuanto antes.
    let mut pending = Vec::with_capacity(buffer.len());
    pending.append(buffer);

    let tx = match client.transaction().await {
        Ok(tx) => tx,
        Err(err) => {
            error!("failed to open transaction: {}", err);
            return;
        }
    };

    for sample in &pending {
        if let Err(err) = tx
            .execute(
                stmt,
                &[
                    &sample.device_mac,
                    &sample.device_name,
                    &sample.ble_ts,
                    &sample.x,
                    &sample.y,
                    &sample.z,
                ],
            )
            .await
        {
            error!("failed to insert sample: {}", err);
            return;
        }
    }

    if let Err(err) = tx.commit().await {
        error!("failed to commit sample batch: {}", err);
        return;
    }
    stats.total_samples += pending.len();
    stats.per_commit_samples = pending.len();
    let elapsed = stats.last_report.elapsed().as_secs_f64();
    if elapsed > 0.0 {
        let current_rate = pending.len() as f64 / elapsed;
        stats.samples_per_second = stats.samples_per_second * 0.8 + current_rate * 0.2;
    }
    stats.last_report = std::time::Instant::now();

    debug!("flushed {} samples", pending.len());
}

// ---------------------------------------------------------------------------
// FFT snapshot persistence
// ---------------------------------------------------------------------------

/// Snapshot FFT para persistir en la base de datos.
/// Cada vec contiene 30 magnitudes (bins 0..29 Hz).
#[derive(Debug, Clone)]
pub struct FftSample {
    pub device_mac: String,
    pub device_name: String,
    pub magnitudes_x: Vec<f32>,
    pub magnitudes_y: Vec<f32>,
    pub magnitudes_z: Vec<f32>,
}

/// Escritor asincrono de snapshots FFT desacoplado del loop BLE.
pub struct FftWriter {
    tx: mpsc::Sender<FftSample>,
}

impl FftWriter {
    /// Crea conexion dedicada a PostgreSQL, crea la tabla y arranca el writer.
    pub async fn connect(database_url: &str) -> Result<Self, Box<dyn Error>> {
        let (client, connection) = tokio_postgres::connect(database_url, NoTls).await?;
        tokio::spawn(async move {
            if let Err(err) = connection.await {
                error!("FFT PostgreSQL connection error: {}", err);
            }
        });
        init_fft_schema(&client).await?;
        let (tx, rx) = mpsc::channel::<FftSample>(512);
        tokio::spawn(async move {
            fft_writer_loop(client, rx).await;
        });
        info!("FFT writer is ready");
        Ok(Self { tx })
    }

    /// Encola un snapshot FFT para persistirlo en segundo plano.
    pub async fn send(&self, sample: FftSample) -> Result<(), mpsc::error::SendError<FftSample>> {
        self.tx.send(sample).await
    }
}

async fn init_fft_schema(client: &Client) -> Result<(), tokio_postgres::Error> {
    client
        .batch_execute(
            "
            CREATE TABLE IF NOT EXISTS fft_snapshots (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                device_mac TEXT NOT NULL,
                device_name TEXT NOT NULL,
                magnitudes_x REAL[] NOT NULL,
                magnitudes_y REAL[] NOT NULL,
                magnitudes_z REAL[] NOT NULL,
                captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (captured_at, id)
            );
            SELECT create_hypertable('fft_snapshots', 'captured_at',
                if_not_exists => TRUE, migrate_data => TRUE);
            CREATE INDEX IF NOT EXISTS idx_fft_snapshots_captured_at
                ON fft_snapshots(captured_at);
            ",
        )
        .await
}

async fn fft_writer_loop(client: Client, mut rx: mpsc::Receiver<FftSample>) {
    let stmt = match client
        .prepare(
            "INSERT INTO fft_snapshots
                (device_mac, device_name, magnitudes_x, magnitudes_y, magnitudes_z)
             VALUES ($1, $2, $3, $4, $5)",
        )
        .await
    {
        Ok(s) => s,
        Err(err) => {
            error!("failed to prepare FFT insert: {}", err);
            return;
        }
    };

    while let Some(s) = rx.recv().await {
        if let Err(err) = client
            .execute(
                &stmt,
                &[
                    &s.device_mac,
                    &s.device_name,
                    &s.magnitudes_x,
                    &s.magnitudes_y,
                    &s.magnitudes_z,
                ],
            )
            .await
        {
            error!("FFT insert error: {}", err);
        }
    }
}
